/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 22-Jun-2019 10:13:02 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS empleado_multiplex_id_seq
;

DROP SEQUENCE IF EXISTS funcion_id_seq
;

DROP SEQUENCE IF EXISTS funcion_sala_id_seq
;

DROP SEQUENCE IF EXISTS multiplex_id_seq
;

DROP SEQUENCE IF EXISTS pago_pk_numpago_seq
;

DROP SEQUENCE IF EXISTS pelicula_id_seq
;

DROP SEQUENCE IF EXISTS reserva_id_seq
;

DROP SEQUENCE IF EXISTS sala_id_seq
;

DROP SEQUENCE IF EXISTS silla_id_seq
;

DROP SEQUENCE IF EXISTS silla_reservada_id_seq
;

DROP SEQUENCE IF EXISTS snack_reserva_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS Cliente CASCADE
;

DROP TABLE IF EXISTS Contrato CASCADE
;

DROP TABLE IF EXISTS Empleado CASCADE
;

DROP TABLE IF EXISTS Empleado_Multiplex CASCADE
;

DROP TABLE IF EXISTS Funcion CASCADE
;

DROP TABLE IF EXISTS Funcion_Sala CASCADE
;

DROP TABLE IF EXISTS Multiplex CASCADE
;

DROP TABLE IF EXISTS Pago CASCADE
;

DROP TABLE IF EXISTS Pelicula CASCADE
;

DROP TABLE IF EXISTS Persona CASCADE
;

DROP TABLE IF EXISTS Reserva CASCADE
;

DROP TABLE IF EXISTS Sala CASCADE
;

DROP TABLE IF EXISTS Silla CASCADE
;

DROP TABLE IF EXISTS Silla_Reservada CASCADE
;

DROP TABLE IF EXISTS Snack CASCADE
;

DROP TABLE IF EXISTS Snack_Reserva CASCADE
;

/* Create Tables */

CREATE TABLE Cliente
(
	fk_persona integer NOT NULL,
	i_numPuntos integer NOT NULL,
	i_numTarjeta varchar(50) NOT NULL,
	d_fechaPuntos varchar(50) NOT NULL
)
;

CREATE TABLE Contrato
(
	id integer NOT NULL,
	v_tipoContrato varchar(100) NOT NULL,
	d_inicioContrato date NOT NULL,
	d_finContrato date NULL,
	i_salario integer NOT NULL
)
;

CREATE TABLE Empleado
(
	fk_persona integer NOT NULL,
	fk_contrato integer NOT NULL,
	n_descuento numeric(4,2) NOT NULL,
	fk_numContrato integer NOT NULL
)
;

CREATE TABLE Empleado_Multiplex
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"empleado_multiplex_id_seq"'::text)::regclass),
	fk_empleado integer NOT NULL,
	fk_multiplex integer NOT NULL,
	f_transferencia timestamp without time zone NOT NULL
)
;

CREATE TABLE Funcion
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"funcion_id_seq"'::text)::regclass),
	v_estado varchar(50) NOT NULL,
	d_proyeccion date NOT NULL,
	fk_pelicula integer NOT NULL,
	t_inicioProyeccion time without time zone NOT NULL,
	t_finProyeccion time without time zone NOT NULL
)
;

CREATE TABLE Funcion_Sala
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"funcion_sala_id_seq"'::text)::regclass),
	fk_funcion integer NOT NULL,
	fk_sala integer NOT NULL
)
;

CREATE TABLE Multiplex
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"multiplex_id_seq"'::text)::regclass),
	v_nombre varchar(100) NOT NULL,
	v_direccion varchar(100) NOT NULL,
	v_ciudad varchar(100) NOT NULL,
	i_minSalas integer NOT NULL,
	i_maxSalas integer NOT NULL
)
;

CREATE TABLE Pago
(
	pk_numPago integer NOT NULL   DEFAULT NEXTVAL(('"pago_pk_numpago_seq"'::text)::regclass),
	t_fechaPago timestamp without time zone NOT NULL,
	i_subtotalPago integer NOT NULL,
	i_totalPago integer NOT NULL,
	i_puntosGanados integer NOT NULL,
	v_metodoPago varchar(50) NOT NULL,
	fk_cliente integer NOT NULL,
	fk_reserva integer NULL
)
;

CREATE TABLE Pelicula
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"pelicula_id_seq"'::text)::regclass),
	v_nombre varchar(150) NOT NULL,
	i_duracion integer NOT NULL,
	tx_sinapsis text NOT NULL,
	v_foto varchar(150) NOT NULL
)
;

CREATE TABLE Persona
(
	pk_cedula integer NOT NULL,
	v_primerNombre varchar(100) NOT NULL,
	v_segundoNombre varchar(100) NULL,
	v_primerApellido varchar(100) NOT NULL,
	v_segundoApellido varchar(100) NOT NULL,
	i_telefono integer NOT NULL,
	v_direccion varchar(100) NOT NULL
)
;

CREATE TABLE Reserva
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"reserva_id_seq"'::text)::regclass),
	v_estado varchar(50) NOT NULL,
	t_inicioReserva timestamp with time zone NOT NULL,
	fk_persona integer NOT NULL
)
;

CREATE TABLE Sala
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"sala_id_seq"'::text)::regclass),
	i_numSala integer NOT NULL,
	i_numPreferencial integer NOT NULL,
	i_numGeneral integer NOT NULL,
	fk_multiplex integer NOT NULL
)
;

CREATE TABLE Silla
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"silla_id_seq"'::text)::regclass),
	pk_numero varchar(3) NOT NULL,
	v_tipo varchar(50) NOT NULL,
	i_orden varchar(50) NOT NULL,
	fk_sala integer NOT NULL
)
;

CREATE TABLE Silla_Reservada
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"silla_reservada_id_seq"'::text)::regclass),
	v_estado varchar(50) NOT NULL,
	fk_silla integer NOT NULL,
	fk_funcion_sala integer NOT NULL,
	fk_reserva integer NOT NULL
)
;

CREATE TABLE Snack
(
	id integer NOT NULL,
	v_tipo varchar(50) NOT NULL,
	v_nombre varchar(50) NOT NULL,
	tx_descripcion text NOT NULL,
	i_precio integer NOT NULL,
	i_puntosOfrecidos integer NULL
)
;

CREATE TABLE Snack_Reserva
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"snack_reserva_id_seq"'::text)::regclass),
	fk_reserva integer NOT NULL,
	fk_snack integer NOT NULL,
	i_cantidad integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Cliente ADD CONSTRAINT PK_Cliente
	PRIMARY KEY (fk_persona)
;

CREATE INDEX IXFK_Cliente_Persona ON Cliente (fk_persona ASC)
;

ALTER TABLE Contrato ADD CONSTRAINT PK_Contrato
	PRIMARY KEY (id)
;

ALTER TABLE Empleado ADD CONSTRAINT PK_Empleado
	PRIMARY KEY (fk_persona)
;

CREATE INDEX IXFK_Empleado_Contrato ON Empleado (fk_numContrato ASC)
;

CREATE INDEX IXFK_Empleado_Persona ON Empleado (fk_persona ASC)
;

ALTER TABLE Empleado_Multiplex ADD CONSTRAINT PK_Empleado_Multiplex
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_Empleado_Multiplex_Empleado ON Empleado_Multiplex (fk_empleado ASC)
;

CREATE INDEX IXFK_Empleado_Multiplex_Multiplex ON Empleado_Multiplex (fk_multiplex ASC)
;

ALTER TABLE Funcion ADD CONSTRAINT PK_Funcion
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_Funcion_Pelicula ON Funcion (fk_pelicula ASC)
;

ALTER TABLE Funcion_Sala ADD CONSTRAINT PK_Funcion_Sala
	PRIMARY KEY (id)
;

ALTER TABLE Funcion_Sala 
  ADD CONSTRAINT Unique_Ket_Funcion_Sala UNIQUE (fk_funcion,fk_sala)
;

CREATE INDEX IXFK_Funcion_Sala_Funcion ON Funcion_Sala (fk_funcion ASC)
;

CREATE INDEX IXFK_Funcion_Sala_Sala ON Funcion_Sala (fk_sala ASC)
;

ALTER TABLE Multiplex ADD CONSTRAINT PK_Multiplex
	PRIMARY KEY (id)
;

ALTER TABLE Pago ADD CONSTRAINT PK_Pago
	PRIMARY KEY (pk_numPago)
;

CREATE INDEX IXFK_Pago_Cliente ON Pago (fk_cliente ASC)
;

CREATE INDEX IXFK_Pago_Reserva ON Pago (fk_reserva ASC)
;

ALTER TABLE Pelicula ADD CONSTRAINT PK_Pelicula
	PRIMARY KEY (id)
;

ALTER TABLE Persona ADD CONSTRAINT PK_Persona
	PRIMARY KEY (pk_cedula)
;

ALTER TABLE Reserva ADD CONSTRAINT PK_Reserva
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_Reserva_Persona ON Reserva (fk_persona ASC)
;

ALTER TABLE Sala ADD CONSTRAINT PK_Sala
	PRIMARY KEY (id)
;

ALTER TABLE Sala 
  ADD CONSTRAINT Unique_key_Sala_Silla UNIQUE (fk_multiplex,i_numSala)
;

CREATE INDEX IXFK_Sala_Multiplex ON Sala (fk_multiplex ASC)
;

ALTER TABLE Silla ADD CONSTRAINT PK_Silla
	PRIMARY KEY (id)
;

ALTER TABLE Silla 
  ADD CONSTRAINT Unique_key_Silla_SillaFuncion UNIQUE (pk_numero,fk_sala)
;

CREATE INDEX IXFK_Silla_Sala ON Silla (fk_sala ASC)
;

ALTER TABLE Silla_Reservada ADD CONSTRAINT PK_Silla_Funcion
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_Silla_Funcion_Reserva ON Silla_Reservada (fk_reserva ASC)
;

CREATE INDEX IXFK_Silla_Funcion_Silla ON Silla_Reservada (fk_silla ASC)
;

CREATE INDEX IXFK_Silla_Reservada_Funcion_Sala ON Silla_Reservada (fk_funcion_sala ASC)
;

ALTER TABLE Snack ADD CONSTRAINT PK_Snack
	PRIMARY KEY (id)
;

ALTER TABLE Snack_Reserva ADD CONSTRAINT PK_Snack_Reserva
	PRIMARY KEY (id)
;

CREATE INDEX IXFK_Snack_Reserva_Reserva ON Snack_Reserva (fk_reserva ASC)
;

CREATE INDEX IXFK_Snack_Reserva_Snack ON Snack_Reserva (fk_snack ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE Cliente ADD CONSTRAINT FK_Cliente_Persona
	FOREIGN KEY (fk_persona) REFERENCES Persona (pk_cedula) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Empleado ADD CONSTRAINT FK_Empleado_Contrato
	FOREIGN KEY (fk_numContrato) REFERENCES Contrato (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Empleado ADD CONSTRAINT FK_Empleado_Persona
	FOREIGN KEY (fk_persona) REFERENCES Persona (pk_cedula) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Empleado_Multiplex ADD CONSTRAINT FK_Empleado_Multiplex_Empleado
	FOREIGN KEY (fk_empleado) REFERENCES Empleado (fk_persona) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Empleado_Multiplex ADD CONSTRAINT FK_Empleado_Multiplex_Multiplex
	FOREIGN KEY (fk_multiplex) REFERENCES Multiplex (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Funcion ADD CONSTRAINT FK_Funcion_Pelicula
	FOREIGN KEY (fk_pelicula) REFERENCES Pelicula (id) ON DELETE No Action ON UPDATE No Action
;
ALTER TABLE funcion ADD CONSTRAINT funcion_unique UNIQUE (
	d_proyeccion,fk_pelicula,t_inicioproyeccion,t_finproyeccion
);

ALTER TABLE Funcion_Sala ADD CONSTRAINT FK_Funcion_Sala_Funcion
	FOREIGN KEY (fk_funcion) REFERENCES Funcion (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Funcion_Sala ADD CONSTRAINT FK_Funcion_Sala_Sala
	FOREIGN KEY (fk_sala) REFERENCES Sala (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Pago ADD CONSTRAINT FK_Pago_Cliente
	FOREIGN KEY (fk_cliente) REFERENCES Cliente (fk_persona) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Pago ADD CONSTRAINT FK_Pago_Reserva
	FOREIGN KEY (fk_reserva) REFERENCES Reserva (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Reserva ADD CONSTRAINT FK_Reserva_Persona
	FOREIGN KEY (fk_persona) REFERENCES Persona (pk_cedula) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Sala ADD CONSTRAINT FK_Sala_Multiplex
	FOREIGN KEY (fk_multiplex) REFERENCES Multiplex (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Silla ADD CONSTRAINT FK_Silla_Sala
	FOREIGN KEY (fk_sala) REFERENCES Sala (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Silla_Reservada ADD CONSTRAINT FK_Silla_Funcion_Reserva
	FOREIGN KEY (fk_reserva) REFERENCES Reserva (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Silla_Reservada ADD CONSTRAINT FK_Silla_Funcion_Silla
	FOREIGN KEY (fk_silla) REFERENCES Silla (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Silla_Reservada ADD CONSTRAINT FK_Silla_Reservada_Funcion_Sala
	FOREIGN KEY (fk_funcion_sala) REFERENCES Funcion_Sala (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Snack_Reserva ADD CONSTRAINT FK_Snack_Reserva_Reserva
	FOREIGN KEY (fk_reserva) REFERENCES Reserva (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Snack_Reserva ADD CONSTRAINT FK_Snack_Reserva_Snack
	FOREIGN KEY (fk_snack) REFERENCES Snack (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE empleado_multiplex_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE funcion_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE funcion_sala_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE multiplex_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE pago_pk_numpago_seq INCREMENT 1 START 1
;

CREATE SEQUENCE pelicula_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE reserva_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE sala_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE silla_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE silla_reservada_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE snack_reserva_id_seq INCREMENT 1 START 1
;

--Contrato
INSERT INTO contrato VALUES (20,'prestación de servicios','2019-10-24','2020-10-24',3000000);
INSERT INTO contrato VALUES (21,'indefinido','2019-10-24','2020-11-26',4100000);
INSERT INTO contrato VALUES (22,'prestación de servicios','2019-10-30','2020-10-24',2000000);